### ISSUE TITLE
Audio delay with HomePod Mini

### ISSUE THREAD

**Issue by aftrmth728** [openairplay/goplay2#17]
Hi there,

Audio is great when used on the single speaker but if I try to play on multiple devices such as a HomePod Mini the audio sync is somewhat off. Is this normal? I understand you mentioned improving the multi-room sync somewhere so if it's an issue that will be fixed at some point that's fine and I understand, I was mostly curious if it's something I have done wrong or I can fix on my end.

Thanks in advance

**Comment by AlbanSeurat** [comment]
Hello, indeed this is normal.

I have another branch in development /audio-sync which will improve the audio sync.

The current development status :
  - works only on Mac (simpler for me to dev/test)
  -  It sync well but you get some jitter (bad noise from time to time) because i have only did a naive approach to tests and measures

i am currently working to detect properly audio skew (drift of clocks ) and a sample rate converter to avoid jitter and noise.

Expect something in September (holidays without computer ;))
